PRODUCTS = {
    "FYPA": {
        "code": "FYPA",
        "name": "Pale Ale Tapp",
        "brewery": "Frydenlund",
        "base_price": 35,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "FYBY": {
        "code": "FYBY",
        "name": "Bayer Tapp",
        "brewery": "Frydenlund",
        "base_price": 35,
        "products_left": 100, 
        "product_type":"foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "FYPL": {
        "code": "FYPL",
        "name": "Pils Tapp",
        "brewery": "Frydenlund",
        "base_price": 35,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "PUHW": {
        "code": "PUHW",
        "name": "Hefe-Weissbier",
        "brewery": "Paulaner",
        "base_price": 45,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "PUDW": {
        "code": "PUDW",
        "name": "Dunkel-Weissbier",
        "brewery": "Paulaner",
        "base_price": 45,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "LEBL": {
        "code": "LEBL",
        "name": "Blonde",
        "brewery": "Leffe",
        "base_price": 43,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "LEBR": {
        "code": "LEBR",
        "name": "Brune",
        "brewery": "Leffe",
        "base_price": 43,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "FZWB": {
        "code": "FZWB",
        "name": "Wiessbier",
        "brewery": "Franziskaner",
        "base_price": 45,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "RAMP": {
        "code": "RAMP",
        "name": "Mocha Porter",
        "brewery": "Rogue Ales",
        "base_price": 44,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "FDAD": {
        "code": "FDAD",
        "name": "All Day IPA",
        "brewery": "Founders",
        "base_price": 40,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "FDDH": {
        "code": "FDDH",
        "name": "Dry Hopped Pale Ale",
        "brewery": "Founders",
        "base_price": 40,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "BHTT": {
        "code": "BHTT",
        "name": "Twisted Thistle IPA",
        "brewery": "Belhaven",
        "base_price": 37,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "SSTP": {
        "code": "SSTP",
        "name": "Taddy Porter",
        "brewery": "Samuel Smith",
        "base_price": 35,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "AMBS": {
    	"code": "AMBS",
        "name": u"Blåbærstout",
        "brewery": "Austmann",
        "base_price": 56,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "AMUP": {
    	"code": "AMUP",
        "name": u"Utpå",
        "brewery": "Austmann",
        "base_price": 38,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "AMSK": {
    	"code": "AMSK",
        "name": u"Sjokolade & kirsebærporter",
        "brewery": "Austmann",
        "base_price": 55,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "AMSE": {
    	"code": "AMSE",
        "name": u"Sea Ese",
        "brewery": "Austmann",
        "base_price": 46,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "AMOA": {
    	"code": "AMOA",
        "name": "Onkel i Amerika",
        "brewery": "Austmann",
        "base_price": 38,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "AMGD": {
    	"code": "AMGD",
        "name": "Tre Gamle Damer",
        "brewery": "Austmann",
        "base_price": 50,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "NCBA": {
    	"code": "NCBA",
        "name": "Brown Ale",
        "brewery": "Newcastle",
        "base_price": 31,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "PWKW": {
    	"code": "PWKW",
        "name": "Kwak",
        "brewery": "Pauwel",
        "base_price": 45,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "MBRR": {
    	"code": "MBRR",
        "name": "Ragnarok",
        "brewery": "Munkebo",
        "base_price": 55,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    },
    "MBFV": {
    	"code": "MBFV",
        "name": "Folkevang",
        "brewery": "Munkebo",
        "base_price": 55,
        "products_left": 100, 
        "product_type": "foo",
        "price_data": [{"sold_units": 0, "adjustment": 0}],
    }
}
